### ISSUE TITLE
Custom Loading Button

### ISSUE THREAD

**Issue by phoward38** [Tychobra/tychobratools#13]
Create a custom action button w/ `UI` & `Server` functions. (Ex use: User clicks button that updates database, then need to be notified that action is running & button can't be clicked again until reset (server side)
- UI (arguments) `loading_button.R`
  - id
  - Change text and/or color when clicked
  - Disable when clicked
- Server `reset_loading_button.R`
  - Arg: id
  - Functionality: button resets back to original state

**Comment by phoward38** [comment]
Created branch `feature/loading_button` & made initial commit.

TO DO:
- [x] Add style & class arguments to pass any css or class
  - Add as string
- [x] Add icon
- [ ] Account for width of button changing w/o custom styling 
- [ ] Create tests for this
  - Run w/ `devtools::check()`
    - Look for existing versions of these

**Comment by phoward38** [comment]
Created PR #14

**Comment by jimbrig** [comment]
> Created branch `feature/loading_button` & made initial commit.
> 
> TO DO:
> 
> * [x]  Add style & class arguments to pass any css or class
>   
>   * Add as string
> * [x]  Add icon
> * [ ]  Account for width of button changing w/o custom styling
> * [ ]  Create tests for this
>   
>   * Run w/ `devtools::check()`
>     
>     * Look for existing versions of these

@phoward38 you'll want to test this with devtools::test (devtools::check is for R CMD CHECK on the whole package, but will still run unit tests as well). However, currently, Andy doesn't have any unit tests for the package.

If you do want to run unit tests I would recommend using testthat along with [shinytest](https://rstudio.github.io/shinytest/articles/shinytest.html) in a tests directory. I have started working with shinytest on unit testing modules and its pretty sweet. See this pretty comprehensive article from RStudio on the subject [here](https://shiny.rstudio.com/articles/integration-testing.html).

For this example, you could use the session$elapse(<time in seconds>) to simulate time passing until the button becomes enabled and then use testthat::expect_equal to check the resulting HTML output against an active button's HTML. The same goes for testing the width change functionality.

**Comment by merlinoa** [comment]
This branch has been merged with master.

Thanks @jimbrig2011 that was an interesting article on testing shiny.  I created a new issue #15 to add a test to this loading button and see how well it works.
