### ISSUE TITLE
add this function to tychobratools

### ISSUE THREAD

**Issue by merlinoa** [Tychobra/tychobratools#2]
https://github.com/Tychobra/shiny-insurance-examples/blob/6e7aed8eddef146a99c367731ebbb6f77b887176/basic-insurer-dashboard/global.R#L27

**Comment by merlinoa** [comment]
call it `valueBoxColor` 

the point of the function is to allow you to be able to set the text and backgroup color of the value box to whatever you want.  With the default `shiny::valueBox()` function you are limited to like 15 color options.

**Comment by RichardHHill** [comment]
I added valueBoxColor to tychobratools. Do you need to give me some kind of access before I push it to github?

**Comment by merlinoa** [comment]
I'm not sure.  what is happening now when you try and push to GitHub?

**Comment by RichardHHill** [comment]
This is the error message:
remote: Permission to Tychobra/tychobratools.git denied to RichardHHill.
fatal: unable to access 'https://github.com/Tychobra/tychobratools.git/': The requested URL returned error: 403

**Comment by merlinoa** [comment]
I changed the default permissions for our organization to write.  Try again now and lmk if it works

**Comment by RichardHHill** [comment]
It worked!
