### ISSUE TITLE
add names map function to tychobratools

### ISSUE THREAD

**Issue by merlinoa** [Tychobra/tychobratools#3]
Add this function to this package https://github.com/Tychobra/exposure-mgmt-pc/blob/e48c76fb2e82af630ab2b2ee22760b0127c878ea/shiny-app/helpers/utils.R#L15

But add a second argument called `names_map` which takes in a data frame with 2 columns:
 
 - "name"
 - "display_name"

 Once you create this function, replace the one defined in `exposure-mgmt-pc` with the `tychobratools` version

**Comment by RichardHHill** [comment]
Put resolved on the commit to exposure-mgmt-pc so it didn't close this issue
