### ISSUE TITLE
create new `value_box_module` 

### ISSUE THREAD

**Issue by merlinoa** [Tychobra/tychobratools#4]
`shinydashboard::valueBox()`es do not appear in the UI until after the value passed to the "value" argument has been calculated.  This results in the valueBox not being on the page on the initial page load, and then it flashed onto the page.  We want the valueBox to be rendered on the initial ui rendering, and then only the "value" and "subtitle" pieces of the valueBox ui will be updated via Shiny. 

Start with `tychobratools::valueBoxColor` and create a module with a couple `shiny::renderText()` / `shiny::textOutput()`.

**Comment by RichardHHill** [comment]
Added with 70373059b2e6b2bcf00eb7c5887859f59415fd2c
