### ISSUE TITLE
update database functions

### ISSUE THREAD

**Issue by merlinoa** [Tychobra/tychobratools#5]
We need to use `dbQuoteLiteral()` before `sqlInterpolate()` in all the functions that query databases: 

- `add_row`
 - `delete_by_id`
 - `update_by_id`

Also `delete_by_id` should be renamed to `delete_by()` and `update_by_id` should be renamed to `update_by`.  In these functions the "id" argument should be replaces with the "by" argument which will take a named list.  e.g. the following call would update all cars with "gears" == 4 and carb == "4".  

`update_by(conn, "mtcars", by = list("gear" = 4, "carb" = 4), .dat = list("vs" = 99))`

**Comment by RichardHHill** [comment]
Finished with fc3d35aaa4c0560998b5792b9f8efef3e57c01c0
