### ISSUE TITLE
Create new `read_by()` function

### ISSUE THREAD

**Issue by merlinoa** [Tychobra/tychobratools#7]
To read data from a table.  Something like this:

```
read_by(conn, tbl_name, cols, by, operator = "AND")
```

Where all the arguments are the same as `update_by` and `delete_by` except the "cols" argument.  "cols" can either be a character vector of column names or "*"

**Comment by RichardHHill** [comment]
Added the function with be57f4b9eba84aeae146c99b0013ea48937f2235

**Comment by merlinoa** [comment]
looks good to me
